# Generated by Django 3.0 on 2021-06-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210628_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content_no',
            field=models.TextField(null=True),
        ),
    ]
